CREATE TABLE [fact].[opportunity] (

	[opportunity_key] varchar(64) NOT NULL, 
	[opportunity_id] varchar(500) NOT NULL, 
	[external_reference] varchar(500) NULL, 
	[title] varchar(2000) NULL, 
	[description] varchar(4000) NULL, 
	[buyer_key] varchar(64) NULL, 
	[source_system] varchar(200) NOT NULL, 
	[category_id] int NULL, 
	[buyer_id] varchar(500) NULL, 
	[buyer_name] varchar(1000) NULL, 
	[category_raw] varchar(500) NULL, 
	[category] varchar(200) NULL, 
	[category_quality_status] varchar(100) NULL, 
	[status_raw] varchar(200) NULL, 
	[status] varchar(200) NULL, 
	[country] varchar(200) NULL, 
	[country_code] varchar(20) NULL, 
	[region] varchar(200) NULL, 
	[published_date] date NULL, 
	[closing_date] date NULL, 
	[days_to_close] int NULL, 
	[currency_code] varchar(20) NULL, 
	[estimated_value] decimal(18,2) NULL, 
	[official_source_url] varchar(2000) NULL, 
	[duplicate_group_hint] varchar(500) NULL, 
	[potential_duplicate_flag] bit NOT NULL, 
	[source_record_id] varchar(500) NULL, 
	[first_seen_at_utc] datetime2(6) NULL, 
	[last_seen_at_utc] datetime2(6) NULL, 
	[silver_run_id] varchar(100) NULL, 
	[silver_processed_at_utc] datetime2(6) NULL, 
	[gold_refreshed_at_utc] datetime2(6) NOT NULL
);